### ISSUE TITLE
Poule doesn't label on "#dibs"

### ISSUE THREAD

**Issue by thaJeztah** [icecrime/poule#23]
We had a feature that automatically added a "status/claimed" label if a user commented `#dibs`. Looks like that is not (yet) supported by poule, e.g. https://github.com/docker/docker/issues/28766#issuecomment-262773724

/cc @icecrime @ehazlett

**Comment by icecrime** [comment]
This can be implemented purely by configuration (left as an exercise for the reader :innocent:).

**Comment by thaJeztah** [comment]
doh! :blush:
