### ISSUE TITLE
Label ARM platform

### ISSUE THREAD

**Issue by alexellis** [icecrime/poule#30]
Hi @icecrime I was chatting to Justin Cormack today and I'd like to raise a PR to categorise Raspberry Pi issues as platform/arm. Are you OK with this?

Can you direct me to the live config?

Potential bonus points for picking up someone running helloworld:latest and getting an error due to wrong architecture. 

https://github.com/docker/docker/issues/29617

**Comment by icecrime** [comment]
SGTM :+1: See https://github.com/docker/docker/blob/master/poule.yml to change the project's configuration!
