### ISSUE TITLE
404 when running in server mode

### ISSUE THREAD

**Issue by davejrt** [icecrime/poule#56]
Hi

Just wondering if there any other specific config that needs to be done to send the webhook to this when running in server mode. I've set it up as per the documentation, but I'm getting 404's when I curl localhost as well as from github.

**Comment by gaocegege** [comment]
Hi, I had the same problem. Did you solve it? @davejrt

**Comment by davejrt** [comment]
@gaocegege that did the trick, thanks for the heads up!
